[package]
name = "dioxus"
version = "0.2.4"
authors = ["Jonathan Kelley"]
edition = "2021"
description = "Core functionality for Dioxus - a concurrent renderer-agnostic Virtual DOM for interactive user experiences"
license = "MIT OR Apache-2.0"
repository = "https://github.com/DioxusLabs/dioxus/"
homepage = "https://dioxuslabs.com"
documentation = "https://dioxuslabs.com"
keywords = ["dom", "ui", "gui", "react", "wasm"]
rust-version = "1.56.0"

[dependencies]
dioxus-core = { path = "./packages/core", version = "^0.2.1" }
dioxus-html = { path = "./packages/html", version = "^0.2.1", optional = true }
dioxus-core-macro = { path = "./packages/core-macro", version = "^0.2.1", optional = true }
dioxus-hooks = { path = "./packages/hooks", version = "^0.2.1", optional = true }

dioxus-desktop = { path = "./packages/desktop", version = "^0.2.3", optional = true }

dioxus-interpreter-js = { path = "./packages/interpreter", version = "^0.2.1", optional = true }

dioxus-liveview = { path = "./packages/liveview", version = "^0.1.0", optional = true }

[features]
default = ["macro", "hooks", "html"]

macro = ["dioxus-core-macro"]
hooks = ["dioxus-hooks"]
html = ["dioxus-html"]
desktop = ["dioxus-desktop"]
liveview = ["dioxus-liveview"]


[workspace]
members = [
    "packages/core",
    "packages/core-macro",
    "packages/html",
    "packages/hooks",
    "packages/desktop",
    "packages/interpreter",
    "packages/liveview",
]

[dev-dependencies]
futures-util = "0.3.21"
log = "0.4.14"
num-format = "0.4.0"
separator = "0.4.1"
serde = { version = "1.0.136", features = ["derive"] }
im-rc = "15.0.0"
anyhow = "1.0.53"
serde_json = "1.0.79"
rand = { version = "0.8.4", features = ["small_rng"] }
tokio = { version = "1.16.1", features = ["full"] }
reqwest = { version = "0.11.9", features = ["json"] }
dioxus = { path = ".", features = ["desktop"] }
fern = { version = "0.6.0", features = ["colored"] }
criterion = "0.3.5"
thiserror = "1.0.30"
env_logger = "0.9.0"

[[bench]]
name = "create"
harness = false

[[bench]]
name = "jsframework"
harness = false

